anchor_version = "0.24.2"
solana_version = "1.9.12"

[features]
seeds = true

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn mocha -b"

[programs.mainnet]
smart_wallet = "oGGQGGbVsdTR1DLkCQoj7Uee3RNBTr9vWtxUZgPMnDi"
token_signer = "NFTUJzSHuUCsMMqMRJpB7PmbsaU7Wm51acdPk2FXMLn"

[programs.devnet]
smart_wallet = "oGGQGGbVsdTR1DLkCQoj7Uee3RNBTr9vWtxUZgPMnDi"
token_signer = "NFTUJzSHuUCsMMqMRJpB7PmbsaU7Wm51acdPk2FXMLn"

[programs.testnet]
smart_wallet = "oGGQGGbVsdTR1DLkCQoj7Uee3RNBTr9vWtxUZgPMnDi"
token_signer = "NFTUJzSHuUCsMMqMRJpB7PmbsaU7Wm51acdPk2FXMLn"

[programs.localnet]
smart_wallet = "oGGQGGbVsdTR1DLkCQoj7Uee3RNBTr9vWtxUZgPMnDi"
token_signer = "NFTUJzSHuUCsMMqMRJpB7PmbsaU7Wm51acdPk2FXMLn"
